name: Data models checks

on:
  push:
    paths:
    - 'datamodels/**'
  pull_request:
    paths:
    - 'datamodels/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install CDDL and CBOR diag tools
      run: gem install --user-install cbor-diag cddl

    - name: set up PATH
      run: echo "$(gem env gempath | cut -d':' -f1)/bin" >> $GITHUB_PATH
      
    - name: Check the attestation results data model
      run: make -C datamodels/attestation-results/grammar
